### ISSUE TITLE
CRD config should contain a config not multiple configs

### ISSUE THREAD

**Issue by pmalek-sumo** [SumoLogic/tailing-sidecar#55]
Currently user [can define the following CRD](https://github.com/SumoLogic/tailing-sidecar/blob/main/operator/docs/configuration.md#named-configurations-using-tailingsidecar)

```yaml
apiVersion: tailing-sidecar.sumologic.com/v1
kind: TailingSidecar
metadata:
  name: tailingsidecar-name
spec:
  configs:
    <config-name0>:
      volume: <volume-name0>
      file: <path-to-tail0>
    <config-name1>:
      volume: <volume-name1>
      file: <path-to-tail1>
    <config-name2>:
      volume: <volume-name2>
      file: <path-to-tail2>
```

and then use it in container annotation:

```yaml
metadata:
  annotations:
    tailing-sidecar: <config-name0>;<config-name1>;<config-name2>
```

In order to simplify the usage for end user the following changes are proposed:

* in API `tailing-sidecar.sumologic.com/v1` object kind `TailingSidecar` should be renamed to `TailingSidecarConfig`
* the config should be used by its name which in pod annotation can be utilized as:

    ```yaml
    apiVersion: tailing-sidecar.sumologic.com/v1
    kind: TailingSidecarConfig
    metadata:
        name: tailingsidecar-config-customname
    spec:
      configs:
        - volume: <volume-name0>
          file: <path-to-tail0>
        - volume: <volume-name1>
          file: <path-to-tail1>
        - volume: <volume-name2>
          file: <path-to-tail2>
    ```

    which could then be used like so:

    ```yaml
    metadata:
    annotations:
        tailing-sidecar: tailingsidecar-config-customname;tailingsidecar-config-customname2
    ```

**Comment by graphex-sumo** [comment]
I think my suggestion would be to approach a CRD like this:
```
apiVersion: tailing-sidecar.sumologic.com/v1
kind: TailingSidecar
metadata:
  name: tailingsidecar-name
spec:
  podSelector: |-
    matchLabels:
      app.kubernetes.io/name: myObservedPod
  config:
    sidecarContainerName0:
      volume: volume-name0
      file: path-to-tail0
      sourceCategory: sourcecategory0
    sidecarContainerName1:
      volume: volume-name1
      file: path-to-tail1
      sourceCategory: sourcecategory1
```

Then the operator would create the following annotations on the pod:
```
metadata:
annotations:
    sumologic.com/tailing-sidecar/sidecarContainerName0: volume=volume-name0,file=path-to-tail0,sourceCategory=sourcecategory0
    sumologic.com/tailing-sidecar/sidecarContainerName1: volume=volume-name1,file=path-to-tail1,sourceCategory=sourcecategory1
```

I'm not sure why there is a separate `volume` and `file` parameter rather than a single `path` parameter, but this seems a simple way to set the most important bits of metadata. If the metadata that can be set on these tailing sidecars changes, (like `path` instead of `file` and `volume`) it is a straightforward change to the annotation with easy backwards compatibility.

**Comment by kkujawa-sumo** [comment]
@graphex-sumo great idea! 

`volume` indicates name of volume which should be mounted to sidecar container to get access to log file
`file` indicates full path to the log file in container file system 
I think that both parameters must be kept but we can rename `file` to `path`

**Comment by kkujawa-sumo** [comment]
There are [some limitations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set) related to key in annotation. 
For mentioned form I received following error:
```
The Pod "pod-with-annotations" is invalid: 
* metadata.annotations: Invalid value: "sumologic.com/tailing-sidecar/sidecarContainerName0": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
* metadata.annotations: Invalid value: "sumologic.com/tailing-sidecar/sidecarContainerName1": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
```

**Comment by graphex-sumo** [comment]
> volume indicates name of volume which should be mounted to sidecar container to get access to log file

In that case, maybe mirroring the standard container `volumeMounts` [API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#volumemount-v1-core) might make things clearer in the CRD, so something like:
```
  config:
    sidecarContainerName0:
      volumeMount:
        name: volume-name0
        subPath: /logs/mylog.log
        mountPath: /logs/mylog.log
      path: /logs/mylog.log
      sourceCategory: sourcecategory0
```
Then to make the annotations clearer and easier to work with:
```
tailing-sidecar.sumologic.com/sidecarContainerName0.volumeMount: 'name=volume-name0 subPath=/logs/mylog.log mountPath=/logs/mylog.log'
tailing-sidecar.sumologic.com/sidecarContainerName0.path: '/logs/mylog.log'
tailing-sidecar.sumologic.com/sidecarContainerName0.sourceCategory: 'sourceCategory0'
```

**Comment by pmalek-sumo** [comment]
> > volume indicates name of volume which should be mounted to sidecar container to get access to log file
> 
> In that case, maybe mirroring the standard container `volumeMounts` [API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#volumemount-v1-core) might make things clearer in the CRD, so something like:
> 
> ```
>   config:
>     sidecarContainerName0:
>       volumeMount:
>         name: volume-name0
>         subPath: /logs/mylog.log
>         mountPath: /logs/mylog.log
>       path: /logs/mylog.log
>       sourceCategory: sourcecategory0
> ```

Just adding my 2 cents: IMHO this would create unnecessary repetition in the config.

**Comment by graphex-sumo** [comment]
Known defaults for the volumeMount API elements would make it so that you didn't have to have repetition, for instance subPath and mountPath would be optional and by default the volume "name" would be mounted at a known location which we define the convention for here. So for example we could use the path `/logs/` as the default mount point for the volume, and the above would simply be:
```
  config:
    sidecarContainerName0:
      volumeMount:
        name: volume-name0
      path: /logs/mylog.log
      sourceCategory: sourcecategory0
 ```
My guess is that users of this project will want the entirety of the volumeMount's flexibility to be available to them. It would be a pretty scary situation if sensitive data happened to be in the same directory as a log, and we forced a customer to mount the entire directory into a tailing sidecar container whose goal in life is to send data to Sumo! If the volumeMount API is available a `subPath` can keep the data that is exposed to the tailing sidecar to a single file.

**Comment by kkujawa-sumo** [comment]
I agree that we can expose full volumeMount API element under `volumeMount` key in the config but there is one more thing to specify - annotation format for known defaults. I think that for known defaults when config has following form 
```
  config:
    sidecarContainerName0:
      volumeMount:
        name: volume-name0
      path: /logs/mylog.log
      sourceCategory: sourcecategory0
```
annotation for volume should have this form:
```
tailing-sidecar.sumologic.com/sidecarContainerName0.volumeMount: 'name=volume-name0'
```
so elements of volumeMount  with default values are not presented in annotation.

**Comment by kkujawa-sumo** [comment]
I think that it will be better to create general rule that adding any key under `sidecarContainerName` key will result in creation of new annotation with `tailing-sidecar.sumologic.com` prefix so for this config:

```
config:
    sidecarContainerName0:
      volumeMount:
        name: volume-name0
        subPath: /logs/mylog.log
        mountPath: /logs/mylog.log
      path: /logs/mylog.log
      sourceCategory: sourcecategory0
```

following annotations will be created:

```
tailing-sidecar.sumologic.com/sidecarContainerName0.volumeMount: 'name=volume-name0 subPath=/logs/mylog.log mountPath=/logs/mylog.log'
tailing-sidecar.sumologic.com/sidecarContainerName0.path: '/logs/mylog.log'
tailing-sidecar.sumologic.com/sidecarContainerName0.sourceCategory: 'sourceCategory0'
```

so for example if not known key will be added to config:

```
config:
    sidecarContainerName0:
      volumeMount:
        name: volume-name0
        subPath: /logs/mylog.log
        mountPath: /logs/mylog.log
      path: /logs/mylog.log
      sourceCategory: sourcecategory0
      not-known-key: not-known-val0
```

following annotations will be added:

```
tailing-sidecar.sumologic.com/sidecarContainerName0.volumeMount: 'name=volume-name0 subPath=/logs/mylog.log mountPath=/logs/mylog.log'
tailing-sidecar.sumologic.com/sidecarContainerName0.path: '/logs/mylog.log'
tailing-sidecar.sumologic.com/sidecarContainerName0.sourceCategory: 'sourceCategory0'
tailing-sidecar.sumologic.com/sidecarContainerName0.not-known-key: 'not-known-val0'
```

@graphex-sumo  What do you think?

**Comment by kkujawa-sumo** [comment]
> I think that it will be better to create general rule that adding any key under `sidecarContainerName` key will result in creation of new annotation with `tailing-sidecar.sumologic.com` prefix so for this config:
> 
> ```
> config:
>     sidecarContainerName0:
>       volumeMount:
>         name: volume-name0
>         subPath: /logs/mylog.log
>         mountPath: /logs/mylog.log
>       path: /logs/mylog.log
>       sourceCategory: sourcecategory0
> ```
> 
> following annotations will be created:
> 
> ```
> tailing-sidecar.sumologic.com/sidecarContainerName0.volumeMount: 'name=volume-name0 subPath=/logs/mylog.log mountPath=/logs/mylog.log'
> tailing-sidecar.sumologic.com/sidecarContainerName0.path: '/logs/mylog.log'
> tailing-sidecar.sumologic.com/sidecarContainerName0.sourceCategory: 'sourceCategory0'
> ```
> 
> so for example if not known key will be added to config:
> 
> ```
> config:
>     sidecarContainerName0:
>       volumeMount:
>         name: volume-name0
>         subPath: /logs/mylog.log
>         mountPath: /logs/mylog.log
>       path: /logs/mylog.log
>       sourceCategory: sourcecategory0
>       not-known-key: not-known-val0
> ```
> 
> following annotations will be added:
> 
> ```
> tailing-sidecar.sumologic.com/sidecarContainerName0.volumeMount: 'name=volume-name0 subPath=/logs/mylog.log mountPath=/logs/mylog.log'
> tailing-sidecar.sumologic.com/sidecarContainerName0.path: '/logs/mylog.log'
> tailing-sidecar.sumologic.com/sidecarContainerName0.sourceCategory: 'sourceCategory0'
> tailing-sidecar.sumologic.com/sidecarContainerName0.not-known-key: 'not-known-val0'
> ```
> 
> @graphex-sumo What do you think?

Support for any not known key causes implantation complications. . Operator SDK is not able to generate manifests for `map[string]interface{}` as type in CRD so I think that we can add support only for known keys - in this case `volumeMount`, `path`, `sourceCategory`.

**Comment by graphex-sumo** [comment]
Generally, CRDs do have complete schemata defined, so it makes sense that unknown keys wouldn't be blindly translated. As the project matures, however, it is good to have a general convention to follow.

I think `mountPath` maybe should have a default location where a volume is mounted in the tailing sidecar's filesystem, and it is the only one which doesn't have a default specified in the [kubernetes api](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#volumemount-v1-core). Whatever default path we define will have to go into the `path` value, so that's something that has to be clear. I used the example of the default `mountPath` being `/logs/` but am open to different proposals. We could also say that `mountPath` is required.

The only other thing i see is that setting `sourceCategory` is something that is defined in another project, and it makes sense to me to use the `sumologic.com` prefix rather than the `tailing-sidecar.sumologic.com` prefix. The issue for the container specific sourceCategory specification is [here](https://github.com/SumoLogic/sumologic-kubernetes-fluentd/issues/169) for reference.

**Comment by kkujawa-sumo** [comment]
@graphex-sumo Working on the new format of CRD for tailing sidecar  operator I got an idea that prefix for annotation could be configurable and defined in `TailingSidecarConfig` and per container annotations could be configured in sidecar configuration under a new key `annotations` so any annotation can be added.

I mean this format:
```yaml
apiVersion: tailing-sidecar.sumologic.com/v1
kind: TailingSidecarConfig
metadata:
  name: tailingsidecar-sample
spec:
  annotationsPrefix: tailing-sidecar.sumologic.com
  podSelector:
    matchLabels:
      tailing-sidecar: "true"
  configs:
    sidecar-0:
      volumeMount:
        name: varlog
        mountPath: /var/log
      path: /var/log/example0.log
      annotations:
        sourceCategory: sourceCategory-0
        annotation-0: "true"
    sidecar-1:
      volumeMount:
        name: varlog
        mountPath: /var/log
      path: /var/log/example1.log
      annotations:
        sourceCategory: sourceCategory-1
        annotation-1: "true"
    sidecar-2:
      volumeMount:
        name: varlogconfig
        mountPath: /varconfig-new-dir/log
        readonly: true
        mountPropagation: HostToContainer
      path: /varconfig-new-dir/log/example2.log
      annotations:
        sourceCategory: sourceCategory-2
        annotation-2: "true"
```

And above configuration will be visible in annotations in following way:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    tailing-sidecar.sumologic.com/sidecar-0.annotation-0: "true"
    tailing-sidecar.sumologic.com/sidecar-0.path: /var/log/example0.log
    tailing-sidecar.sumologic.com/sidecar-0.sourceCategory: sourceCategory-0
    tailing-sidecar.sumologic.com/sidecar-0.volumeMount: name=varlog readonly=false
      mountPath=/var/log
    tailing-sidecar.sumologic.com/sidecar-1.annotation-1: "true"
    tailing-sidecar.sumologic.com/sidecar-1.path: /var/log/example1.log
    tailing-sidecar.sumologic.com/sidecar-1.sourceCategory: sourceCategory-1
    tailing-sidecar.sumologic.com/sidecar-1.volumeMount: name=varlog readonly=false
      mountPath=/var/log
    tailing-sidecar.sumologic.com/sidecar-2.annotation-2: "true"
    tailing-sidecar.sumologic.com/sidecar-2.path: /varconfig-new-dir/log/example2.log
    tailing-sidecar.sumologic.com/sidecar-2.sourceCategory: sourceCategory-2
    tailing-sidecar.sumologic.com/sidecar-2.volumeMount: name=varlogconfig readonly=false
```

Regarding default value of `MountPath` for VolumeMount, k8s API requires `Name` and `MountPath` to be provided for VolumeMount, it is defined in following way in "k8s.io/api/core/v1"
```go
// VolumeMount describes a mounting of a Volume within a container.
type VolumeMount struct {
    // This must match the Name of a Volume.
    Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
    // Mounted read-only if true, read-write otherwise (false or unspecified).
    // Defaults to false.
    // +optional
    ReadOnly bool `json:"readOnly,omitempty" protobuf:"varint,2,opt,name=readOnly"`
    // Path within the container at which the volume should be mounted.  Must
    // not contain ':'.
    MountPath string `json:"mountPath" protobuf:"bytes,3,opt,name=mountPath"`
    // Path within the volume from which the container's volume should be mounted.
    // Defaults to "" (volume's root).
    // +optional
    SubPath string `json:"subPath,omitempty" protobuf:"bytes,4,opt,name=subPath"`
    // mountPropagation determines how mounts are propagated from the host
    // to container and the other way around.
    // When not set, MountPropagationNone is used.
    // This field is beta in 1.10.
    // +optional
    MountPropagation *MountPropagationMode `json:"mountPropagation,omitempty" protobuf:"bytes,5,opt,name=mountPropagation,casttype=MountPropagationMode"`
    // Expanded path within the volume from which the container's volume should be mounted.
    // Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container's environment.
    // Defaults to "" (volume's root).
    // SubPathExpr and SubPath are mutually exclusive.
    // +optional
    SubPathExpr string `json:"subPathExpr,omitempty" protobuf:"bytes,6,opt,name=subPathExpr"`
}
```

I decided to use `VolumeMount `which is defined "k8s.io/api/core/v1"  as type for Sidecar `VolumeMount` as potential small changes in k8s definition of `VolumeMount` (like adding additional field) could be handled without changes in code for operator.  It can be desribed in documentation that it is k8s definition of `VolumeMount` (to which people are used to).

I did the same adding `PodSelector` in definition of `TailingSidecarConfig` and it significantly simplified implementation and mechanism of handling `PodSelector` which are used in k8s are reused in Tailing Sidecar operator.

Operator SDK generates CRD using definitions of types in code so it generates CRD with this parameters for VolumeMount:
```yaml
required:
- mountPath
- name
```

**Comment by kkujawa-sumo** [comment]
Currently Tailing Sidecar Operator does not add annotations with `path` and `volumeMount` information,  so it works in following way:

```
apiVersion: tailing-sidecar.sumologic.com/v1
kind: TailingSidecarConfig
metadata:
  name: tailingsidecar-sample
spec:
  annotationsPrefix: tailing-sidecar.sumologic.com
  podSelector:
    matchLabels:
      tailing-sidecar: "true"
  configs:
    sidecar-0:
      volumeMount:
        name: varlog
        mountPath: /var/log
      path: /var/log/example0.log
      annotations:
        sourceCategory: sourceCategory-0
        annotation-0: "true"
    sidecar-1:
      volumeMount:
        name: varlog
        mountPath: /var/log
      path: /var/log/example1.log
      annotations:
        sourceCategory: sourceCategory-1
        annotation-1: "true"
    sidecar-2:
      volumeMount:
        name: varlogconfig
        mountPath: /varconfig-new-dir/log
        readonly: true
        mountPropagation: HostToContainer
      path: /varconfig-new-dir/log/example2.log
      annotations:
        sourceCategory: sourceCategory-2
        annotation-2: "true"
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    tailing-sidecar.sumologic.com/sidecar-0.annotation-0: "true"
    tailing-sidecar.sumologic.com/sidecar-0.sourceCategory: sourceCategory-0
    tailing-sidecar.sumologic.com/sidecar-1.annotation-1: "true"
    tailing-sidecar.sumologic.com/sidecar-1.sourceCategory: sourceCategory-1
    tailing-sidecar.sumologic.com/sidecar-2.annotation-2: "true"
    tailing-sidecar.sumologic.com/sidecar-2.sourceCategory: sourceCategory-2
```
